dist: bionic
language: minimal
branches:
  only:
  - master
before_install:
- sudo apt-get update
- sudo apt-get install -y texlive-latex-base texlive-latex-extra
jobs:
  include:
  - stage: build
    script:
    - pdflatex examples.tex
before_deploy:
- git tag -f ${TRAVIS_BRANCH}-latest
deploy:
  provider: releases
  api_key:
    secure: RDzzTBIY9OAAa6PlOXeERYyincS56KM4H56oPxdOTSRIhgQt4dCjcnoFX1UDXmNQg48xZ7xIh3rBW0QZT8SUD+3XUFWVifid8YVjwYMIWhzFjiNmHWB5t2k/Wmuk5gYK5NP4H3EC8h875MTDjDgaXd/ZfQxdWmp75UoZF6Nvxn0hC9fnyV5+yMiQ2BFDbVv5yaATqZfK0sn0j1Zmzrsyk7HVgUsWyGdKpA1J3zSLOCnYFxKDREjS7bZLNQPxe7kX02UD/Jv7BikBvkswdP8Tmr8inAA1vusV3iN8q1ctbNA5gXTOt6ttsTsb8kd0fo3V8AS+rmIei+m0wYtWklwquZ5dW8MgGZG5UDt+sfENaZ1cvrYKEaEm3ircS9egfILzE0P6lnbHOHwFJIrGRf5/XLRqgdxYUQe5VvfMARq1pygEQHCTN14/Z94LlaV95IsCFbfC3jHvmRwhdCloy6Iv3GmYRJTOEwEdGWerQawfNDalRAP4R31FBMA5votZ6t+kqERtOmwguP1KPZSGJzS2qXbyr/yp+2TVbJ1+XLiSTAlQjgSkcx4Wgz+afBgTlzjVbTi4KMVU6YX1bjDmmFr/LRqkvZsA6TX/L/gbCR8+XkGnQdwzT9TEbkqfuoWczhQg+YbLOVNuunxZEFzTUUURzsdMxFz3eHarvPKPHeLYEf0=
  file: examples.pdf
  on:
    repo: riichi/tikz-riichi
  skip_cleanup: true
  overwrite: true
